# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOt-dKbz6nzpDoC0hATK5LUXuZxVntXg
"""

!pip install pmdarima

from zipfile import ZipFile
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.ar_model import ar_select_order, AutoReg
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.holtwinters import ExponentialSmoothing, Holt, SimpleExpSmoothing
from statsmodels.tsa.exponential_smoothing.ets import ETSModel
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.metrics import mean_absolute_error
import warnings
warnings.filterwarnings("ignore")
from pmdarima import auto_arima

from zipfile import ZipFile

with ZipFile("train.csv.zip", "r") as zip_ref:
    zip_ref.extractall()

print("ZIP file extracted successfully!")

import pandas as pd

df = pd.read_csv("train.csv")

df.head()

df.shape

df.info()

df["date"] = pd.to_datetime(df["date"])
print(df.dtypes)

df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["dayofweek"] = df["date"].dt.dayofweek

df.head()

df["sales"].describe()

import matplotlib.pyplot as plt

monthly_sales = df.groupby("month")["sales"].mean()

plt.figure(figsize=(8,5))
plt.plot(monthly_sales.index, monthly_sales.values, marker="o")
plt.title("Average Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Average Sales")
plt.grid(True)
plt.show()

df.isnull().sum()

df.duplicated().sum()

monthly_sales = df.groupby("month")["sales"].mean()

import matplotlib.pyplot as plt

plt.figure(figsize=(6,3))
plt.plot(monthly_sales.index,
         monthly_sales.values,
         marker="o")

plt.title("Average Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Average Sales")
plt.grid(True)

plt.show()

store_sales = df.groupby("store")["sales"].mean()

plt.figure(figsize=(6,3))
# Using a list of colors for each bar
colors = plt.cm.viridis(store_sales.index / float(len(store_sales)))
store_sales.plot(kind="bar", color=colors)

plt.title("Average Sales by Store")
plt.xlabel("Store")
plt.ylabel("Average Sales")

plt.show()

import numpy as np
top_items = df.groupby("item")["sales"].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(6,3))
# Generate a distinct color for each bar from a colormap
colors = plt.cm.viridis(np.linspace(0, 1, len(top_items)))
top_items.plot(kind="bar", color=colors)

plt.title("Top 10 Selling Items")
plt.xlabel("Item")
plt.ylabel("Average Sales")

plt.show()

# Sort data by date
df = df.sort_values("date")

# Aggregate sales by date
daily_sales = df.groupby("date")["sales"].sum().reset_index()

daily_sales.head()

train = daily_sales.iloc[:-30]
test = daily_sales.iloc[-30:]

print("Train Shape:", train.shape)
print("Test Shape:", test.shape)

from statsmodels.tsa.arima.model import ARIMA

model = ARIMA(train["sales"], order=(5,1,0))
model_fit = model.fit()

print(model_fit.summary())

forecast = model_fit.forecast(steps=30)

forecast

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
import numpy as np

mae = mean_absolute_error(test["sales"], forecast)
rmse = np.sqrt(mean_squared_error(test["sales"], forecast))

print("MAE:", mae)
print("RMSE:", rmse)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.plot(test["date"], test["sales"], label="Actual Sales", marker="o")
plt.plot(test["date"], forecast, label="Predicted Sales", marker="x")

plt.title("Actual vs Predicted Sales")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.legend()
plt.grid(True)

plt.show()
